### PR TITLE
Trace methods in CompInfo's TypeCollector impl

### LINKED ISSUE #410: Typedef type in whitelisted function's argument not in generated bindings, compilation failure
Input:

```c++
namespace JS {
class Value;
}
typedef enum {} JSWhyMagic;
namespace JS {
class Value {
public:
  void a(JSWhyMagic);
};
}
```

Output with `--enable-cxx-namespaces` and `--whitelist-type 'JS::Value'`:

```rust
/* automatically generated by rust-bindgen */

#![feature(untagged_unions)]

pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod JS {
        #[allow(unused_imports)]
        use self::super::super::root;
        #[repr(C)]
        #[derive(Debug, Copy)]
        pub struct Value {
            pub _address: u8,
        }
        #[test]
        fn bindgen_test_layout_Value() {
            assert_eq!(::std::mem::size_of::<Value>() , 1usize);
            assert_eq!(::std::mem::align_of::<Value>() , 1usize);
        }
        extern "C" {
            #[link_name = "_ZN2JS5Value1aE10JSWhyMagic"]
            pub fn Value_a(this: *mut root::JS::Value,
                           arg1: root::JS::JSWhyMagic);
        }
        impl Clone for Value {
            fn clone(&self) -> Self { *self }
        }
        impl Value {
            #[inline]
            pub unsafe fn a(&mut self, arg1: root::JS::JSWhyMagic) {
                Value_a(&mut *self, arg1)
            }
        }
    }
}
```

Compilation of output fails with:

```
$ rustc --crate-type lib ./js.rs
error[E0412]: type name `root::JS::JSWhyMagic` is undefined or not in scope
  --> ./js.rs:24:34
   |
24 |                            arg1: root::JS::JSWhyMagic);
   |                                  ^^^^^^^^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `JSWhyMagic` found in your project; maybe you misspelled the name or forgot to import an external crate?

error[E0412]: type name `root::JS::JSWhyMagic` is undefined or not in scope
  --> ./js.rs:31:46
   |
31 |             pub unsafe fn a(&mut self, arg1: root::JS::JSWhyMagic) {
   |                                              ^^^^^^^^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `JSWhyMagic` found in your project; maybe you misspelled the name or forgot to import an external crate?

error: aborting due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by fitzgen**
Fixes #410 

r? @emilio

### CODE REVIEW

**Comment by fitzgen** [comment]
Added two more commits cleaning up more of the type tracing.

The only TODO left about type tracing is for `CompInfo`'s vtable.

**Comment by fitzgen** [comment]
It isn't clear to me what needs to happen with regards to vtables here. It seems like they should already be handled via the base's tracing?

File: libbindgen/src/ir/ty.rs [hunk 1]
```diff
@@ -914,13 +914,24 @@ impl TypeCollector for Type {
...
-            ref other @ _ => {
-                debug!("<Type as TypeCollector>::collect_types: Ignoring: \
-                       {:?}",
-                       other);
+            TypeKind::Enum(ref en) => {
+                if let Some(repr) = en.repr() {
+                    types.insert(repr);
+                }
+            }
+            TypeKind::UnresolvedTypeRef(_, _, Some(id)) => {
```
Comment (emilio) [inline libbindgen/src/ir/ty.rs]: We could just mark `UnresolvedTypeRef` as unreachable I think.

File: libbindgen/src/ir/item.rs [hunk 2]
```diff
@@ -205,7 +205,12 @@ impl TypeCollector for Item {
             ItemKind::Var(ref var) => {
                 types.insert(var.ty());
             }
-            _ => {} // FIXME.
+            ItemKind::Module(_) => {
+                // Module -> children edges are "weak", and we do not want to
+                // trace them. If we did, then whitelisting wouldn't work as
+                // expected: everything in every module would end up
+                // whitelisted.
```
Comment (emilio) [inline libbindgen/src/ir/item.rs]: This is only true because we start tracing through the root module right? we should be able of making that exception? Anyway it's fine for now.

File: libbindgen/src/ir/comp.rs [hunk 3]
```diff
@@ -954,6 +954,10 @@ impl TypeCollector for CompInfo {
             types.insert(var);
         }
 
-        // FIXME(emilio): Methods, VTable?
+        for method in self.methods() {
+            types.insert(method.signature);
+        }
+
+        // FIXME(emilio): VTable?
```
Comment (emilio) [inline libbindgen/src/ir/comp.rs]: Yeah, I think every type that could potentially be used in the vtable would be caught by the bases or the methods, so you should be able to remove this comment.

File: libbindgen/src/ir/item.rs (hunk 2 above)
Comment (fitzgen) [inline libbindgen/src/ir/item.rs]: Its because we trace the `parent_id` to find the containing module, which will then end up tracing everything in the module, and the module's parent module which will end up tracing everything in that module, etc etc.

Comment (fitzgen) [inline libbindgen/src/ir/item.rs]: And also because of tracing the root module too, I suppose.

File: libbindgen/src/ir/ty.rs (hunk 1 above)
Comment (fitzgen) [inline libbindgen/src/ir/ty.rs]: Yeah, I wasn't thinking... That invariant should definitely hold here.

File: libbindgen/src/ir/comp.rs (hunk 3 above)
Comment (fitzgen) [inline libbindgen/src/ir/comp.rs]: Will remove.
