### PR TITLE
Use the generated root module via a relative path

### LINKED ISSUE #96: Namespaces work only if the bindings are the root.
The `use root;` we generate is wrong if the bindings are not the root of the crate, we should use a relative import.

### PR DESCRIPTION
**Pull request by fitzgen**
We previously generated uses of the root module with absolute paths:

    use root;

However this only works if the generated bindings are the root of the
crate. If they were in some submodule then that path would not be
valid. They are now generated relative to the current module, like this:

    use self::super::super::root;

Fixes #96

r? @emilio

### CODE REVIEW

File: libbindgen/src/codegen/mod.rs [hunk 1]
```diff
@@ -22,19 +22,40 @@ use std::borrow::Cow;
...
     let root_ident = ctx.rust_ident(&root);
-    quote_item!(ctx.ext_cx(), #[allow(unused_imports)] use $root_ident;)
-        .unwrap()
+
+    let super_ = aster::AstBuilder::new().id("super");
+    let supers = module
+        .ancestors(ctx)
+        .filter(|id| ctx.resolve_item(*id).is_module())
+        .map(|_| super_.clone())
+        .chain(iter::once(super_.clone()));
```
Comment (emilio) [inline libbindgen/src/codegen/mod.rs]: nit: I don't think you need this `clone`.

File: libbindgen/src/codegen/mod.rs [hunk 2]
```diff
@@ -22,19 +22,40 @@ use std::borrow::Cow;
...
+use std::iter;
 use std::mem;
 use std::ops;
 use syntax::abi::Abi;
 use syntax::ast;
 use syntax::codemap::{Span, respan};
 use syntax::ptr::P;
 
-fn root_import(ctx: &BindgenContext) -> P<ast::Item> {
+fn root_import(ctx: &BindgenContext, module: &Item) -> P<ast::Item> {
```
Comment (emilio) [inline libbindgen/src/codegen/mod.rs]: Probably `assert!(module.is_module())`?

**Comment by fitzgen** [comment]
Thanks, @emilio !
