### PR TITLE
Reintroduce bitfield accessors

### LINKED ISSUE #519: Re-introduce bitfield accessors.
The refactor at #512 is dropping them intentionally since the way bitfields were handled was so broken.

They need to be re-implemented, it's not exceptionally hard, but it's a bit of work.

### PR DESCRIPTION
**Pull request by fitzgen**
This commit reintroduces accessor methods for bitfields in the generated
bindings.

Fixes #519 

r? @emilio

### CODE REVIEW

**Comment by fitzgen** [comment]
Tests are failing because the travis ci gcc doesn't seem to understand `static_assert`:

```
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-o" "/tmp/bindgen/debug/build/bindgen-integration-cd0402279e5ba3c7/out/cpp/Test.o" "-c" "cpp/Test.cc"
cargo:warning=In file included from cpp/Test.cc:1:0:
cargo:warning=cpp/Test.h:40:14: error: expected constructor, destructor, or type conversion before ‘(’ token
cargo:warning=cpp/Test.h:41:14: error: expected constructor, destructor, or type conversion before ‘(’ token
cargo:warning=cpp/Test.h:52:14: error: expected constructor, destructor, or type conversion before ‘(’ token
cargo:warning=cpp/Test.h:53:14: error: expected constructor, destructor, or type conversion before ‘(’ token
cargo:warning=cpp/Test.h:70:14: error: expected constructor, destructor, or type conversion before ‘(’ token
cargo:warning=cpp/Test.h:71:14: error: expected constructor, destructor, or type conversion before ‘(’ token
ExitStatus(ExitStatus(256))
```

**Comment by fitzgen** [comment]
Updated with an attempt to pass `-std=c++11` through to the compiler in `build.rs`.

**Comment by fitzgen** [comment]
> Updated with an attempt to pass -std=c++11 through to the compiler in build.rs.

Strange... my local Fedora gcc has support for `-std=c++11` but it seems that the travis ci gcc doesn't. Not sure what version of gcc it is, but the easiest thing to do here is just remove the static asserts in the C++, since they aren't essential.

**Comment by fitzgen** [comment]
Alright, removed the `static_assert`s from the C++ and CI is green. Ready when you are, @emilio :)

**Comment by emilio** [comment]
> Alright, removed the static_asserts from the C++ and CI is green. Ready when you are, @emilio :)

Instead of that, I think compiling with a newer `-std` should do it. I think the GCC Travis has is a bit older and doesn't have `static_assert`s by default.

**Comment by fitzgen** [comment]
> Instead of that, I think compiling with a newer -std should do it. I think the GCC Travis has is a bit older and doesn't have static_asserts by default.

I tried that, and travis's gcc complained that it didn't understand `-std` and refused to compile :-/

File: src/codegen/mod.rs [hunk 1]
```diff
@@ -791,44 +788,127 @@ impl<'a> Bitfield<'a> {
...
+        let setter_name = ctx.ext_cx()
+            .ident_of(&format!("set_{}", &name));
+        let field_ident = ctx.ext_cx().ident_of(field_name);
+
+        let field_int_ty = match field_layout.size {
+            8 => quote_ty!(ctx.ext_cx(), u64),
+            4 => quote_ty!(ctx.ext_cx(), u32),
+            2 => quote_ty!(ctx.ext_cx(), u16),
+            1 => quote_ty!(ctx.ext_cx(), u8),
+            _ => panic!("physical field containing bitfields should be sized \
```
Comment (emilio) [inline src/codegen/mod.rs]: well, I guess someone could make bindgen panic with something like: `__u128 foo: 128` or something? If so, maybe we just want to skip the getter/setter?

(Not a big deal landing as-is for now)

File: src/codegen/mod.rs [hunk 2]
```diff
@@ -791,44 +788,127 @@ impl<'a> Bitfield<'a> {
...
+        let mask: usize = ((1usize << width) - 1usize) << offset;
+
+        let impl_item = quote_item!(
+            ctx.ext_cx(),
+            impl XxxIgnored {
+                #[inline]
+                pub fn $getter_name(&self) -> $bitfield_ty {
+                    let mask = $mask as $field_int_ty;
+                    let field_val: $field_int_ty = unsafe {
+                        ::$prefix::mem::transmute(self.$field_ident)
```
Comment (emilio) [inline src/codegen/mod.rs]: nice way to not having to care about the alignment ;)

File: src/codegen/mod.rs (hunk 1 above)
Comment (fitzgen) [inline src/codegen/mod.rs]: Oh good catch, I didn't think of that. I'll make an E-Easy issue to fix it.

**Comment by fitzgen** [comment]
Thanks for the review! :) @bors-servo r=emilio
