### PR TITLE
Do not treat parent struct as a module for nested structs

### LINKED ISSUE #311: `error: ambiguous associated type` in generated bindings
Flags: `--enable-cxx-namespaces`

Input:

```c++
struct jsval_layout {
  struct {};
};
```

Output:

```rust
/* automatically generated by rust-bindgen */

pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    #[repr(C)]
    #[derive(Debug, Copy)]
    pub struct jsval_layout {
        pub __bindgen_anon_1: root::jsval_layout::jsval_layout__bindgen_ty_1,
    }
    #[repr(C)]
    #[derive(Debug, Copy)]
    pub struct jsval_layout__bindgen_ty_1 {
        pub _address: u8,
    }
    #[test]
    fn bindgen_test_layout_jsval_layout__bindgen_ty_1() {
        assert_eq!(::std::mem::size_of::<jsval_layout__bindgen_ty_1>() ,
                   1usize);
        assert_eq!(::std::mem::align_of::<jsval_layout__bindgen_ty_1>() ,
                   1usize);
    }
    impl Clone for jsval_layout__bindgen_ty_1 {
        fn clone(&self) -> Self { *self }
    }
    #[test]
    fn bindgen_test_layout_jsval_layout() {
        assert_eq!(::std::mem::size_of::<jsval_layout>() , 1usize);
        assert_eq!(::std::mem::align_of::<jsval_layout>() , 1usize);
    }
    impl Clone for jsval_layout {
        fn clone(&self) -> Self { *self }
    }
}
```

Compilation error:

```
$ rustc --crate-type lib ./js.rs
error[E0223]: ambiguous associated type
 --> ./js.rs:9:31
  |
9 |         pub __bindgen_anon_1: root::jsval_layout::jsval_layout__bindgen_ty_1,
  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ambiguous associated type
  |
  = note: specify the type using the syntax `<root::jsval_layout as Trait>::jsval_layout__bindgen_ty_1`

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by fitzgen**
This fixes `ItemCanonicalPath` to return paths of the form `[module*,
item]` rather than `[item*, item]`. That is, there will only be module
names before the item's name, rather than also other arbitrary item
names (such as parent structs).

Fixes #311

r? @emilio

### CODE REVIEW

File: libbindgen/src/ir/item.rs [hunk 1]
```diff
@@ -1181,50 +1182,15 @@ impl ItemCanonicalPath for Item {
...
-            let is_alias = match *self.expect_type().kind() {
-                TypeKind::Alias(..) => true,
-                _ => false,
-            };
-            debug_assert!(is_alias, "How can this ever happen?");
-            parent_path.pop().unwrap();
-        }
-        parent_path.push(self.name(ctx).within_namespaces().get());
-
-        parent_path
```
Comment (fitzgen) [inline libbindgen/src/ir/item.rs]: Pretty happy with the amount of code I was able to remove here :)

**Comment by emilio** [comment]
@bors-servo: r+

Awesome cleanup :)

**Comment by fitzgen** [comment]
Thanks :)
