### PR TITLE
Handle templated aliases.

### LINKED ISSUE #83: Failing test case w/ replaces and using in namespaces
cc @emilio 

Input:

```c++
// bindgen-flags: -- -x c++ -std=c++14

namespace JS {
    namespace detail {
        template <typename T>
        struct Wrapped {
            T t;
        };
    }

    template <typename T>
    struct Rooted {
        detail::Wrapped<T> ptr;
    };
}

namespace JS {
    namespace detail {
        /**
         * <div rustbindgen replaces="Wrapped" />
         */
        template <typename T>
        using Wrapped_simple = T;
    }
}
```

Output:

```rust
/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Rooted<T> {
    pub ptr: Wrapped<T>,
}
```

I'd expect there to be a `pub type Wrapped<T> = T;` in the output.

### PR DESCRIPTION
**Pull request by emilio**
Fixes #83.

cc @fitzgen 
r? @nox

### CODE REVIEW

File: src/ir/item.rs [hunk 1]
```diff
@@ -277,11 +278,20 @@ impl Item {
                     TypeKind::Named(ref name, _) => {
                         return name.to_owned();
                     }
-                    _ => {}
-                }
-
-                ty.name().map(ToOwned::to_owned)
-                         .unwrap_or_else(|| format!("_bindgen_ty{}", self.id()))
+                    // We really codegen and use the inner type, so use an empty
+                    // base name so codegen doesn't get confused.
```
Comment (fitzgen) [inline src/ir/item.rs]: The start of this sentence has some funky grammar that prevents me from understanding it.

Is it supposed to be

> We really *want* codegen *to* ~~and~~ use the inner type, ...

?

File: tests/headers/template_alias_namespace.hpp [hunk 2]
```diff
@@ -0,0 +1,13 @@
+// bindgen-flags: --enable-cxx-namespaces -- -std=c++14
```
Comment (fitzgen) [inline tests/headers/template_alias_namespace.hpp]: What happens if we don't have `--enable-cxx-namespaces` here? Will the generated rust code be all in the same namespace, or will it fail, or something else?

Comment (emilio) [inline tests/headers/template_alias_namespace.hpp]: It's the exact same test that `tests/headers/template_alias.hpp`, just that flag changes, so you can see the output right away :)

File: src/ir/item.rs (hunk 1 above)
Comment (emilio) [inline src/ir/item.rs]: I meant something like "We call codegen on the inner type, and since we use the parent chain to generate the canonical name, and we don't want this to appear, and can't be referenced itself from another type (we point to the actual alias for that), there's no need to generate a name for it".

Does that make sense?

Comment (fitzgen) [inline src/ir/item.rs]: Thanks, I think I understand much better now. I would phrase it like this:

> We call codegen on the inner type, but we do not want this alias's name to appear in the canonical name just because it is in the type's parent chain, so we use an empty base name.

How is that?

(Thanks for painting this bike shed with me)

**Comment by nox** [comment]
@emilio r=me once it is rebased.
