### PR TITLE
Avoid mangling name for tpl class member. Fix #68

### LINKED ISSUE #68: Avoid trying to generate mangling name for members of template class
This may lead to libclang crash as mentioned in #67.

### PR DESCRIPTION
**Pull request by upsuper**
Not sure whether it is the right thing to do.

### CODE REVIEW

**Comment by emilio** [comment]
Hmm... So I though this avoided getting the mangling for unspecialized methods, but this also avoids that in specialized methods.

I'm fine with not getting symbols for non-specialized templates, because it makes no particular sense (and I guess are the ones that crash), but I guess we can still parse the ones for specialized templates? (Though I think we don't use them yet?).

TLDR: Does a check like `self.is_template() && self.specialized() != self` instead of just `self.is_template()` still make the crash go away?

**Comment by emilio** [comment]
Otherwise I'm fine with merging this, I guess.

**Comment by emilio** [comment]
Oh, and thanks for digging into this btw :-)

**Comment by upsuper** [comment]
The minimal reproduce code is:
```c++
template<class M> struct A;
template<class C> struct A<void(C::*)()> { static int v; };
```
and it crashes at the static attribute `v`. Given `A<void(C::*)()>` looks like a specified template (correct me if I'm wrong. I'm not very familiar with these concepts), I suppose checking specifized wouldn't fix the crash?

**Comment by emilio** [comment]
Well, it's not specialized completely, since you still don't know the `C` type.

Does something like:

```cpp
template<class M> struct A;
template<>
struct A<int> {
    static int foo;
};
```

still crash?

**Comment by emilio** [comment]
Also, even if it still crashes, can you add a comment on the `cursor_mangling` function saying why we're returning early? I don't want anybody to remove it accidentally :)

**Comment by upsuper** [comment]
That doesn't crash. But how can we check whether one template is fully specialized? It seems to me `specialized()` is for finding the less specialized one the template is from.

**Comment by emilio** [comment]
Hm... that's right. I think you can do:

```
fn is_complete_template_specialization(&self) -> bool {
    self.num_template_args() > 0
}
```

File: src/clang.rs [hunk 1]
```diff
@@ -136,6 +136,19 @@ impl Cursor {
...
+    pub fn is_fully_specialized_template(&self) -> bool {
+        self.is_template() && self.num_template_args() > 0
+    }
+
+    pub fn is_in_non_fully_specialized_template(&self) -> bool {
+        if self.is_toplevel() {
+            return false;
+        }
+        let parent = self.semantic_parent();
+        (parent.is_template() && !parent.is_fully_specialized_template()) ||
```
Comment (emilio) [inline src/clang.rs]: You can drop the `parent.is_template()` check here, since is already part of `is_fully_specialized_template()`.

**Comment by emilio** [comment]
r=me with that

@bors-servo: delegate+

File: src/clang.rs (hunk 1 above)
Comment (upsuper) [inline src/clang.rs]: You can't, because `is_fully_specialized_template()` is negated, so if you remove `parent.is_template()`, it would return `true` for non-templates.

**Comment by emilio** [comment]
You're right,

@bors-servo: r+
