### PR TITLE
Generate better opaque blobs in the face of non-type parameters

### LINKED ISSUE #569: Non-type template parameters and failing layout tests
### Input C/C++ Header

```C++
template <int, typename> struct a {};
enum { b };
namespace JS {
template <typename c> using d = a<b, c>;
template <typename c> class e { d<c> f; };
class AutoIdVector : e<int> {};
}
```

### Bindgen Invokation

```
$ bindgen input.hpp -- -std=c++14
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

pub const b: _bindgen_ty_1 = _bindgen_ty_1::b;
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum _bindgen_ty_1 { b = 0, }
pub type JS_d = ();
#[repr(C)]
pub struct JS_e {
    pub f: JS_d,
}
#[repr(C)]
pub struct JS_AutoIdVector {
    pub _base: JS_e,
}
#[test]
fn bindgen_test_layout_JS_AutoIdVector() {
    assert_eq!(::std::mem::size_of::<JS_AutoIdVector>() , 1usize , concat ! (
               "Size of: " , stringify ! ( JS_AutoIdVector ) ));
    assert_eq! (::std::mem::align_of::<JS_AutoIdVector>() , 1usize , concat !
                ( "Alignment of " , stringify ! ( JS_AutoIdVector ) ));
}
#[test]
fn __bindgen_test_layout_JS_e_instantiation_16() {
    assert_eq!(::std::mem::size_of::<JS_e>() , 1usize , concat ! (
               "Size of template specialization: " , stringify ! ( JS_e ) ));
    assert_eq!(::std::mem::align_of::<JS_e>() , 1usize , concat ! (
               "Alignment of template specialization: " , stringify ! ( JS_e )
               ));
}
```

Compiling with `--test` and running the generated layout tests results in these failures:

```
running 2 tests
test root::JS::bindgen_test_layout_AutoIdVector ... FAILED
test root::__bindgen_test_layout_e_instantiation_16 ... FAILED

failures:

---- root::JS::bindgen_test_layout_AutoIdVector stdout ----
	thread 'root::JS::bindgen_test_layout_AutoIdVector' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `1`): Size of: AutoIdVector', ./js.rs:22
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- root::__bindgen_test_layout_e_instantiation_16 stdout ----
	thread 'root::__bindgen_test_layout_e_instantiation_16' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `1`): Size of template specialization: root :: JS :: e', ./js.rs:31


failures:
    root::JS::bindgen_test_layout_AutoIdVector
    root::__bindgen_test_layout_e_instantiation_16

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured
```

### Expected Results

Although we generally can't support non-type template parameters and instantiations of templates with such parameters, we shouldn't be generating code + layout tests that fail. We need to do a better job of detecting this and emitting an opaque blob instead, or even completely skipping this stuff in codegen (which we do some of the time but not always it seems).

### PR DESCRIPTION
**Pull request by fitzgen**
When instantiating templates whose definitions have non-type generic parameters, prefer the layout of the instantiation type to the garbage we get from the definition's layout. In general, an instantiation's layout will always be a better choice than the definition's layout, regardless of non-type parameters.

Fixes #569

r? @emilio

### CODE REVIEW

File: src/codegen/mod.rs [hunk 1]
```diff
@@ -2376,9 +2376,7 @@ impl ToRustTy for TemplateInstantiation {
             debug_assert!(ctx.resolve_type_through_type_refs(decl)
```
Comment (emilio) [inline src/codegen/mod.rs]: Let's use `match` here instead of if let ... else return?

File: src/codegen/mod.rs [hunk 2]
```diff
@@ -561,7 +561,13 @@ impl CodeGenerator for Type {
                     let layout = self.layout(ctx).unwrap_or_else(Layout::zero);
                     BlobTyBuilder::new(layout).build()
                 } else {
-                    inner_item.to_rust_ty(ctx)
+                    let inner_rust_ty = inner_item.to_rust_ty(ctx);
+                    if inner_rust_ty == aster::AstBuilder::new().ty().unit() {
```
Comment (emilio) [inline src/codegen/mod.rs]: This conditional is hacky enough it deserves at least a comment. But I really think we should just check the type to see if it's a template instantiation? Or at least, given `to_rust_ty` should never generate `unit` types unless that, what about `debug_assert!`ing instead?

Comment (fitzgen) [inline src/codegen/mod.rs]: Will do.

I was also thinking that `ToRustTy::to_rust_ty` should return an `Option` or a `Result`, and then instead of ever returning `()` we would return `None`. This is a slightly more invasive change, however, and I can do it if you want, but don't feel like going out of my way at the moment :-P

File: src/codegen/mod.rs (hunk 1 above)
Comment (fitzgen) [inline src/codegen/mod.rs]: Sure thing.

**Comment by fitzgen** [comment]
Thanks for the super speedy review :)

@bors-servo r=emilio
