### PR TITLE
Handle re-declaration of a global variable. Fix #47

### LINKED ISSUE #47: Deduplicate statics
Test case:

```cpp
extern int foo;
extern int foo;
```

In the real case where I hit this, the two declarations are in separate files. Still, I believe that multiple identical declarations are legal in C++.

Code generated by bindgen with commit 1e26a8a0ef76656dc3567eb68a954a701fbb42c8:
```rust
extern "C" {
    pub static mut foo: ::std::os::raw::c_int;
    pub static mut foo: ::std::os::raw::c_int;
}
```

Building code like this makes rustc emit an error:

```rust
error[E0428]: a value named `systick_millis_count` has already been defined in this module
    --> src/bindings.rs:3231:5
     |
3207 |     pub static mut systick_millis_count: ::std::os::raw::c_uint;
     |     ------------------------------------------------------------ previous definition of `systick_millis_count` here
...
3231 |     pub static mut systick_millis_count: ::std::os::raw::c_uint;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ already defined
```

### LINKED ISSUE #48: Deduplicate names of overloaded virtual methods
Test case:

```cpp
class Stream {
    public:
    virtual void write(char* string);
    virtual void write(void* buffer, unsigned int size);
};
```

Code generated by bindgen 1e26a8a0ef76656dc3567eb68a954a701fbb42c8:

```rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct Struct_Stream {
    pub _vftable: *const _vftable_Struct_Stream,
}
#[repr(C)]
pub struct _vftable_Struct_Stream {
    pub write: unsafe extern "C" fn(this: *mut ::std::os::raw::c_void,
                                    string: *mut ::std::os::raw::c_char),
    pub write: unsafe extern "C" fn(this: *mut ::std::os::raw::c_void,
                                    buffer: *mut ::std::os::raw::c_void,
                                    size: ::std::os::raw::c_uint),
}
impl ::std::clone::Clone for Struct_Stream {
    fn clone(&self) -> Self { *self }
}
#[test]
fn bindgen_test_layout_Struct_Stream() {
    assert_eq!(::std::mem::size_of::<Struct_Stream>() , 8usize);
    assert_eq!(::std::mem::align_of::<Struct_Stream>() , 8usize);
}
```

Struct fields with the same name are an error in Rust. Similar code fails with:

```rust
    --> src/bindings.rs:1987:5
     |
1985 |     pub write: unsafe extern "C" fn(this: *mut ::std::os::raw::c_void, b: u8)
     |     - `write` first declared here
1986 |                    -> usize,
1987 |     pub write: unsafe extern "C" fn(this: *mut ::std::os::raw::c_void,
     |     ^ field already declared
```

The field names should probably be deduplicated by appending an integer, like for names of non-virtual methods.

CC @emilio @nox

### PR DESCRIPTION
**Pull request by jeanphilippeD**

### CODE REVIEW

File: src/codegen/mod.rs [hunk 1]
```diff
@@ -265,23 +277,31 @@ impl CodeGenerator for Var {
                ctx: &BindgenContext,
                result: &mut CodegenResult,
                item: &Item) {
-        let name = item.canonical_name(ctx);
+        let canonical_name = item.canonical_name(ctx);
+
+        // TODO: Maybe warn here if there's a type mismatch
```
Comment (Yamakaky) [inline src/codegen/mod.rs]: Clang already does it, I think

Comment (jeanphilippeD) [inline src/codegen/mod.rs]: Thank you for your comment.
Do you mean the TODO is not necessary?
I guess it would result in a compile error in the C or C++ code.

Comment (Yamakaky) [inline src/codegen/mod.rs]: Yeah, from what I remember bindgen prints clang warnings, so there is no need to do an other warning

**Comment by emilio** [comment]
Looks great, thanks!

@bors-servo: r+
