### PR TITLE
Never use spaces in generated name (fixes #844)

### LINKED ISSUE #844: Layout test can contain whitespace inside the function name which causes unexpected token error
### Input C/C++ Header

```C++
template<typename T>
class Foo {
  T* m;
};

class Bar {
  Foo<const char> m;
};
```

### Bindgen Invocation

```
$ bindgen input.hpp
```

### Actual Results

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo<T> {
    pub m: *mut T,
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct Bar {
    pub m: Foo<::std::os::raw::c_char>,
}
#[test]
fn bindgen_test_layout_Bar() {
    assert_eq!(::std::mem::size_of::<Bar>() , 8usize , concat ! (
               "Size of: " , stringify ! ( Bar ) ));
    assert_eq! (::std::mem::align_of::<Bar>() , 8usize , concat ! (
                "Alignment of " , stringify ! ( Bar ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const Bar ) ) . m as * const _ as usize } ,
                0usize , concat ! (
                "Alignment of field: " , stringify ! ( Bar ) , "::" ,
                stringify ! ( m ) ));
}
impl Clone for Bar {
    fn clone(&self) -> Self { *self }
}
#[test]
fn __bindgen_test_layout_Foo_open0_const char_close0_instantiation() {
    assert_eq!(::std::mem::size_of::<Foo<::std::os::raw::c_char>>() , 8usize ,
               concat ! (
               "Size of template specialization: " , stringify ! (
               Foo<::std::os::raw::c_char> ) ));
    assert_eq!(::std::mem::align_of::<Foo<::std::os::raw::c_char>>() , 8usize
               , concat ! (
               "Alignment of template specialization: " , stringify ! (
               Foo<::std::os::raw::c_char> ) ));
}
```

The last layout test function contains a whitespace in its name.

### Expected Results

It should generate valid function name.

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

File: src/ir/context.rs [hunk 1]
```diff
@@ -1391,7 +1391,12 @@ impl<'ctx> BindgenContext<'ctx> {
             _ => return None,
         };
 
-        let spelling = ty.spelling();
+        let mut spelling = ty.spelling();
```
Comment (emilio) [inline src/ir/context.rs]: just:

```rust
let spelling = ty.spelling().replace(' ', "_");
```

File: tests/headers/template.hpp [hunk 2]
```diff
@@ -1,11 +1,26 @@
...
+
 void bar(Foo<int, int> foo);
 
+struct C {
+    B<unsigned int> mB;
+    B<const int*> mBConstPtr;
+    B<const int> mBConst;
+    B<volatile int> mBVolatile;
+    B<const bool> mBConstBool;
+    B<const char16_t> mBConstChar;
```
Comment (upsuper) [inline tests/headers/template.hpp]: It might probably better to have more, at least something like `unsigned long long1 which has whitespace unrelated to cv, as well as things like `long double` to cover non-interger types, and probably `const decltype(nullptr)` might be a good one to test as well.
