### PR TITLE
codegen: Don't implement variadic methods.

### LINKED ISSUE #402: Variadic argument member function failure.
It happens when the variadic argument function is defined as a class member function.  Then like the below, rust-bindgen tries to generate `...` argument for a non-foreign function, which current rustc doesn't support.

Example:

Header:
```Rust
// In some class
String& AppendWithFormat(const char* formatString, ...);
```

Generated code:
```Rust
// In some impl
    #[inline]
    pub unsafe fn AppendWithFormat(&mut self,
                                   formatString:
                                       *const ::std::os::raw::c_char, ...)
     -> *mut Urho3D_String {
        Urho3D_String_AppendWithFormat(&mut *self, formatString)
    }
```

Compiling the above generated code:
```
error: expected pattern, found `...`
    --> src/generated.rs:1203:71
     |
1203 |                                        *const ::std::os::raw::c_char, ...)
```

I think we should disable code generation for this case and emit a warning for now, unless there is an easy solution for this.

### PR DESCRIPTION
**Pull request by emilio**
Fixes #402 

r? @fitzgen

### CODE REVIEW

File: libbindgen/src/codegen/mod.rs [hunk 1]
```diff
@@ -1295,6 +1295,12 @@ impl MethodCodegen for Method {
             _ => panic!("How in the world?"),
         };
 
+        // Do not generate variadic methods, since rust does not allow
+        // implementing them, and we don't do a good job at it anyway.
+        if signature.is_variadic() {
+            return;
```
Comment (fitzgen) [inline libbindgen/src/codegen/mod.rs]: Might be worth a `debug!(...)` here.

File: libbindgen/tests/expectations/tests/variadic-method.rs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+    pub _address: u8,
+}
+#[test]
+fn bindgen_test_layout_Bar() {
+    assert_eq!(::std::mem::size_of::<Bar>() , 1usize);
+    assert_eq!(::std::mem::align_of::<Bar>() , 1usize);
+}
+extern "C" {
+    #[link_name = "_ZN3Bar3fooEPKcz"]
+    pub fn Bar_foo(this: *mut Bar, fmt: *const ::std::os::raw::c_char, ...);
```
Comment (fitzgen) [inline libbindgen/tests/expectations/tests/variadic-method.rs]: I think the point was supposed to be *not* to generate this, right?

First of all, we can't support variadics. Second of all, is this codegen'd a named type named `...`? Need to implement the checks that named types are actually valid named types...

Comment (emilio) [inline libbindgen/tests/expectations/tests/variadic-method.rs]: Nope, the point was to not generate the wrapper method that calls this. Generating variadic functions otherwise is fine.

Comment (emilio) [inline libbindgen/tests/expectations/tests/variadic-method.rs]: (And nope, it's not a named type, rust's AST can represent variadic functions, which is what we use here)

Comment (fitzgen) [inline libbindgen/tests/expectations/tests/variadic-method.rs]: Hm yeah I guess the tests are passing which means it compiles. Color me surprised.
