### PR TITLE
Fix blacklisting and fix instantiations in the template analysis

### LINKED ISSUE #662: Even some more stylo derived errors
### Input C/C++ Header

```C++
template <class T> class RefPtr { T a; };
template <class T> class nsMainThreadPtrHolder { T a; };
template <class T> class nsMainThreadPtrHandle {
  RefPtr<nsMainThreadPtrHolder<T>> mPtr;
};
```

### Bindgen Invokation

Complicated, will get back with a minimal invokation in a bit.

### Actual Results

```rust
/* automatically generated by rust-bindgen */

pub use self::root::*;
pub use self::root::mozilla::*;
pub use self::root::mozilla::css::*;
pub use self::root::mozilla::dom::*;
use atomic_refcell::AtomicRefCell;
use data::ElementData;
pub type ServoUnsafeCell<T> = ::std::cell::UnsafeCell<T>;
pub type ServoCell<T> = ::std::cell::Cell<T>;
pub type ServoNodeData = AtomicRefCell<ElementData>;

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct RefPtr<T> {
        pub a: T,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct nsMainThreadPtrHolder<T> {
        pub a: T,
    }
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct nsMainThreadPtrHandle {
        pub mPtr: root::RefPtr<root::nsMainThreadPtrHolder<T>>,
    }
}
```

Which results in compilation errors like

```
error[E0412]: cannot find type `T` in this scope
  --> stylo_structs.rs:30:60
   |
30 |         pub mPtr: root::RefPtr<root::nsMainThreadPtrHolder<T>>,
   |                                                            ^ not found in this scope
```

-->

### Expected Results

Some compilation errors from the `raw-line` insertions, but all type parameters that get referenced should exist.

### PR DESCRIPTION
**Pull request by fitzgen**
For correctness, I now realize that we need to consider the full transitive closure of whitelisted items, including blacklisted items that we would otherwise not consider as whitelisted. We need this so that the data flow propagates properly through dependencies that may or may not be blacklisted.

This means that tracing infrastructure needs to trace items regardless if they are hidden or blacklisted. It is now the responsibility of consumers of a traversal to filter out such items if they are unwanted. I did this by turning the `ir::context::WhitelistedItems` type alias into a proper struct that performs the filtering. This approach avoids changing the many callers of whitelisted items traversal iteration.

Additionally, and equally importantly, I realized that the case of template instantiations' template usages were subtly wrong. Before this commit, we only considered a template argument used if it itself was a template parameter. This breaks down in the face of template instantiations used as arguments to another template instantiation. If the inner instantiation used a template parameter, we would accidentally lose that usage. For example:

```c++
template <class T>
struct Foo {
    // Direct usage of a template parameter T in an instantiation always worked.
    Bar<T> member;

    // While indirect usage of a template parameter nested within another
    // instantiation did NOT previously work.
    Bar< Qux<T> > another_member;
};
```

The solution is to take the union of each template arguments' template usages, not the template arguments themselves but only if they were themselves a template parameter. Obvious in retrospect!

Fixes #662.

r? @emilio

### CODE REVIEW

**Comment by fitzgen** [comment]
Looks like llvm.org is down???

```
<snip>
--2017-04-25 02:49:47--  (try:10)  http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
Connecting to llvm.org (llvm.org)|192.17.58.186|:80... failed: Connection timed out.
Retrying.
--2017-04-25 02:52:07--  (try:11)  http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
Connecting to llvm.org (llvm.org)|192.17.58.186|:80... failed: Connection timed out.
Retrying.
--2017-04-25 02:54:26--  (try:12)  http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
Connecting to llvm.org (llvm.org)|192.17.58.186|:80... 
```

**Comment by fitzgen** [comment]
Ok, looks like llvm.org is back up, CI is green \o/

File: src/ir/context.rs [hunk 1]
```diff
@@ -646,12 +687,22 @@ impl<'ctx> BindgenContext<'ctx> {
...
+            .resolve(self)
+            .id();
+
         self.used_template_parameters
             .as_ref()
             .expect("should have found template parameter usage if we're in codegen")
             .get(&item)
             .map(|items_used_params| items_used_params.contains(&template_param))
-            .unwrap_or_else(|| self.resolve_item(item).is_hidden(self))
+            .unwrap_or(false)
```
Comment (fitzgen) [inline src/ir/context.rs]: I always forget about `map_or`...

**Comment by fitzgen** [comment]
> that monotone framework is going to drive us crazy ;)

I find it *much* easier to deal with than libclang ;)

**Comment by fitzgen** [comment]
@bors-servo r=emilio

Thanks for review!

**Comment by fitzgen** [comment]
> > that monotone framework is going to drive us crazy ;)
> 
> I find it much easier to deal with than libclang ;)

Additionally, I think it is getting pretty stable now.
