### PR TITLE
Ensure that every item is in some module's children list

### LINKED ISSUE #769: Testing instantiation with argument of a type that we didn't generate bindings for
### Input C/C++ Header

```C++
namespace JS {
template <typename a> class Rooted { a b; };
class AutoValueVector : Rooted<int> {
  using Vec = int;
  using c = Rooted<Vec>;
};
}
```

### Bindgen Invocation

Some complicated thing from SM bindings. Will see what more minimal flags required are and report back.

### Actual Results

```rust
/* automatically generated by rust-bindgen */

#![feature(const_fn)]
pub use self::root::*;
unsafe impl Sync for JSClass {}
unsafe impl Sync for JSFunctionSpec {}
unsafe impl Sync for JSNativeWrapper {}
unsafe impl Sync for JSPropertySpec {}
unsafe impl Sync for JSTypedMethodJitInfo {}

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod JS {
        #[allow(unused_imports)]
        use self::super::super::root;
        #[repr(C)]
        #[derive(Debug, Copy, Clone)]
        pub struct Rooted<a> {
            pub b: a,
            pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<a>>,
        }
    }
    #[test]
    fn __bindgen_test_layout_Rooted_instantiation_1() {
        assert_eq!(::std::mem::size_of::<root::JS::Rooted<::std::os::raw::c_int>>()
                   , 4usize , concat ! (
                   "Size of template specialization: " , stringify ! (
                   root::JS::Rooted<::std::os::raw::c_int> ) ));
        assert_eq!(::std::mem::align_of::<root::JS::Rooted<::std::os::raw::c_int>>()
                   , 4usize , concat ! (
                   "Alignment of template specialization: " , stringify ! (
                   root::JS::Rooted<::std::os::raw::c_int> ) ));
    }
    #[test]
    fn __bindgen_test_layout_Rooted_instantiation_2() {
        assert_eq!(::std::mem::size_of::<root::JS::Rooted<root::JS::AutoValueVector_Vec>>()
                   , 4usize , concat ! (
                   "Size of template specialization: " , stringify ! (
                   root::JS::Rooted<root::JS::AutoValueVector_Vec> ) ));
        assert_eq!(::std::mem::align_of::<root::JS::Rooted<root::JS::AutoValueVector_Vec>>()
                   , 4usize , concat ! (
                   "Alignment of template specialization: " , stringify ! (
                   root::JS::Rooted<root::JS::AutoValueVector_Vec> ) ));
    }
}
```

And then this fails to compile because we don't emit any definition for `AutoValueVector_Vec`:

```
error[E0412]: cannot find type `AutoValueVector_Vec` in module `root::JS`
  --> js.rs:42:70
   |
42 |         assert_eq!(::std::mem::align_of::<root::JS::Rooted<root::JS::AutoValueVector_Vec>>()
   |                                                                      ^^^^^^^^^^^^^^^^^^^ not found in `root::JS`
```

### Expected Results

We probably should just avoid emitting tests of any instantiation involving non-whitelisted things.

### PR DESCRIPTION
**Pull request by fitzgen**
Previously, if an item's parent was not a module (eg a nested class definition whose parent it the outer class definition) and the parent was not whitelisted but the item was transitively whitelisted, then we could generate uses of the item without emitting any definition for it. This could happen because we were relying on the outer type calling for code generation on its inner types, but that relies on us doing code generation for the outer type, which won't happen if the outer type is not whitelisted.

This commit avoids this gotcha by ensuring that all items end up in a module's children list, and so will be code generated even if their parent is not whitelisted.

This does have the downside of changing the relative order of some of the emitted code, and so this has a big diff (as will the next bindgen update for downstream dependencies) but I actually think the newer order makes more sense, for what that is worth.

Fixes #769

r? @emilio

### CODE REVIEW

**Comment by fitzgen** [comment]
Looks like this uncovered a bug with static variables whose type is a template type parameter. Coming up with a fix for that too.

**Comment by fitzgen** [comment]
Huh, now I'm getting tripped up by the recent naming scheme change for the layout tests for template instantiations. It appears it isn't as unique as we'd hoped.

**Comment by fitzgen** [comment]
Going to use the overloaded function counter instead.

File: src/ir/context.rs [hunk 1]
```diff
@@ -348,14 +348,31 @@ impl<'ctx> BindgenContext<'ctx> {
         let is_template_instantiation =
             is_type && item.expect_type().is_template_instantiation();
 
-        // Be sure to track all the generated children under namespace, even
-        // those generated after resolving typerefs, etc.
+        // Ensure that every item (other than the root module) is in a module's
+        // children list.
```
Comment (emilio) [inline src/ir/context.rs]: Maybe point to the issue this is fixing or something? it may be slightly counter-intuitive otherwise.

File: src/ir/context.rs [hunk 2]
```diff
@@ -348,14 +348,31 @@ impl<'ctx> BindgenContext<'ctx> {
...
+
             if let Some(mut parent) = self.items.get_mut(&item.parent_id()) {
                 if let Some(mut module) = parent.as_module_mut() {
                     module.children_mut().push(item.id());
+                    added_as_child = true;
                 }
             }
+
+            if !added_as_child {
+                if let Some(mut current_module) = self.items.get_mut(&self.current_module) {
```
Comment (emilio) [inline src/ir/context.rs]: You can probably unwrap here instead of asserting below?

**Comment by emilio** [comment]
This seems to make the order of the generated bindings not match across libclang versions though, and thus CI is red.

**Comment by fitzgen** [comment]
Thanks for review! (Sorry it's such a huge diff)

> This seems to make the order of the generated bindings not match across libclang versions though, and thus CI is red.

I'll make the children an `ItemSet` instead of a `Vec`. This has two advantages:

1. An `ItemSet` is ordered, so we should get deterministic iteration of a module's children (and therefore emit them in that deterministic order during codegen)

2. It disallows duplicate entries (which *should* be harmless, but its so easy to prevent that it seems crazy not to prevent it).

**Comment by fitzgen** [comment]
I expect CI will still be red, since I need to get the diffs for libclang 3.8 and 3.9

**Comment by fitzgen** [comment]
This *might* need some more updates for other libclang versions, but I'm not 100%.

In any case, it probably deserves a second glance, since a bunch of code changed from the version you reviewed before, @emilio.

r? @emilio

**Comment by fitzgen** [comment]
Ok, tests for other libclang versions should be good to go.

File: tests/expectations/tests/enum_and_vtable_mangling.rs [hunk 3]
```diff
@@ -34,3 +34,7 @@ impl Clone for C {
 impl Default for C {
     fn default() -> Self { unsafe { ::std::mem::zeroed() } }
 }
+extern "C" {
+    #[link_name = "_ZN1C5matchEv"]
+    pub fn C_match(this: *mut ::std::os::raw::c_void);
```
Comment (emilio) [inline tests/expectations/tests/enum_and_vtable_mangling.rs]: So, these are somewhat surprising, because AIUI they aren't referenced from anywhere... Perhaps it's not a big deal...

File: src/ir/context.rs [hunk 4]
```diff
@@ -1038,13 +1105,14 @@ impl<'ctx> BindgenContext<'ctx> {
                         let sub_item = Item::new(sub_id,
                                                  None,
                                                  None,
-                                                 template_decl_id,
+                                                 self.current_module,
```
Comment (emilio) [inline src/ir/context.rs]: So we'll instantiate templates against the current module? Even if they're nested? That looks suspicious. The parentage relationship for...

```rust
struct Foo {
    template<typename T> struct Bar { T baz; };
    Bar<int> m_member;
};
```

So, if I'm reading this correctly, we'll scope `Bar<int>` to the gloal scope, not to `Foo`, right? Can you justify that? If it doesn't matter (which I think it could be true). Could you add a comment?

File: tests/expectations/tests/enum_and_vtable_mangling.rs (hunk 3 above)
Comment (fitzgen) [inline tests/expectations/tests/enum_and_vtable_mangling.rs]: These get generated because the functions are no longer defined inline in the header, just declared -- maybe I am misunderstanding you?

File: src/ir/context.rs (hunk 4 above)
Comment (fitzgen) [inline src/ir/context.rs]: I just changed from one well-known-but-sort-of-bogus parent to another well-known-but-sort-of-bogus parent.

They used to always be parented by the template definition, which doesn't really make sense either, just happened to be handy when the "real" parent wasn't.

I can definitely add a comment.

Comment (fitzgen) [inline src/ir/context.rs]: Comment added.

File: tests/expectations/tests/enum_and_vtable_mangling.rs (hunk 3 above)
Comment (emilio) [inline tests/expectations/tests/enum_and_vtable_mangling.rs]: Err, my fault, for some reason I thought this was a destructor... nevermind.

**Comment by fitzgen** [comment]
Thanks!
